# Generated by Django 4.1.7 on 2023-10-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
