# Generated by Django 4.1.7 on 2023-10-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_comment_id_comment_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
